                                            Assignment No.8

1. Write a Python Program to Add Two Matrices?

In [19]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


2. Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np
A = [[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]]

B = [[15, 28, 18, 2],
	[16, 27, 23, 0],
	[4, 15, 9, 1]]

result= [[0,0,0,0],
		[0,0,0,0],
		[0,0,0,0]]

result = np.dot(A,B)
for r in result:
	print(r)


[ 59 127  91   5]
[164 337 241  14]
[269 547 391  23]


                                                    OR

In [8]:
A = [[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]]

B = [[15, 28, 18, 2],
	[16, 27, 23, 0],
	[4, 15, 9, 1]]

result= [[0,0,0,0],
		[0,0,0,0],
		[0,0,0,0]]
for i in range(len(A)):
     for j in range(len(B[0])):
         for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r)


[59, 127, 91, 5]
[164, 337, 241, 14]
[269, 547, 391, 23]


3. Write a Python Program to Transpose a Matrix?

In [11]:
matrix = [[1, 5], [2, 8], [6, 3]]
transpose = [[0, 0, 0], [0, 0, 0]]
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        transpose[j][i] = matrix[i][j]

print(transpose)


[[1, 2, 6], [5, 8, 3]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
my_str = input("Enter a string: ")  
words = my_str.split()  
words.sort()  
for word in words:  
   print(word)

Balaghat
Deshmukh
From
I
Renu
am


5. Write a Python Program to Remove Punctuation From a String?

In [18]:
import string
def remove_punctuations(text):
    for c in string.punctuation:
        text = text.replace(c,"")
    return text

text = "Hello! I am Renu Deshmukh. From Balaghat?"
print("Original text:")
print(text)
result = remove_punctuations(text)
print("After removing Punctuations from the said string:")
print(result)


Original text:
Hello! I am Renu Deshmukh. From Balaghat?
After removing Punctuations from the said string:
Hello I am Renu Deshmukh From Balaghat
